# Generated by Django 6.1.1 on 2026-10-04 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, verbose_name='Empreinte du code')),
                ('channels', models.CharField(blank=True, max_length=32, verbose_name="Canaux d'envoi")),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Essais')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code de réinitialisation',
                'verbose_name_plural': 'Codes de réinitialisation',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_reset_user_recent')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], max_length=16, verbose_name='Fournisseur')),
                ('uid', models.CharField(max_length=255, verbose_name='Identifiant chez le fournisseur')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail communiqué')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lié le')),
                ('last_login_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière connexion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte social',
                'verbose_name_plural': 'Comptes sociaux',
                'constraints': [models.UniqueConstraint(fields=('provider', 'uid'), name='uniq_social_provider_uid')],
            },
        ),
    ]
