# Generated by Django 6.1.1 on 2026-09-29 20:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A Positif'), ('A-', 'A Négatif'), ('B+', 'B Positif'), ('B-', 'B Négatif'), ('AB+', 'AB Positif'), ('AB-', 'AB Négatif'), ('O+', 'O Positif'), ('O-', 'O Négatif')], max_length=3, verbose_name='Groupe sanguin du receveur')),
                ('units_needed', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Poches nécessaires')),
                ('units_collected', models.PositiveSmallIntegerField(default=0, verbose_name='Poches collectées')),
                ('urgency', models.CharField(choices=[('critical', 'Critique (pronostic vital engagé)'), ('urgent', 'Urgente'), ('normal', 'Normale')], default='urgent', max_length=10, verbose_name='Urgence')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('fulfilled', 'Satisfaite'), ('cancelled', 'Annulée')], default='open', max_length=10, verbose_name='Statut')),
                ('notes', models.CharField(blank=True, help_text='Contexte utile aux équipes, sans donnée identifiant le patient.', max_length=500, verbose_name='Précisions')),
                ('needed_by', models.DateTimeField(blank=True, null=True, verbose_name='Nécessaire avant le')),
                ('search_radius_km', models.PositiveSmallIntegerField(default=20, help_text="Distance maximale entre l'établissement et les donneurs sollicités.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Rayon de recherche (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Clôturée le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_requests', to='users.healthfacility', verbose_name='Établissement demandeur')),
            ],
            options={
                'verbose_name': 'Demande de sang',
                'verbose_name_plural': 'Demandes de sang',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A Positif'), ('A-', 'A Négatif'), ('B+', 'B Positif'), ('B-', 'B Négatif'), ('AB+', 'AB Positif'), ('AB-', 'AB Négatif'), ('O+', 'O Positif'), ('O-', 'O Négatif')], max_length=3, verbose_name='Groupe sanguin')),
                ('sex', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], help_text='Détermine le délai minimal entre deux dons.', max_length=1, verbose_name='Sexe')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('is_available', models.BooleanField(default=True, help_text="Le donneur accepte d'être sollicité pour des demandes urgentes.", verbose_name='Disponible')),
                ('latitude', models.FloatField(blank=True, help_text='Degrés décimaux WGS 84 (-90 à 90).', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Degrés décimaux WGS 84 (-180 à 180).', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('location_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Position mise à jour le')),
                ('last_donation_date', models.DateField(blank=True, null=True, verbose_name='Date du dernier don')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Donneur',
                'verbose_name_plural': 'Donneurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepte de donner'), ('declined', 'Décline'), ('cancelled', 'Désistement'), ('donated', 'Don effectué'), ('no_show', "Ne s'est pas présenté")], max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Répondu le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sang.bloodrequest', verbose_name='Demande')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sang.donor', verbose_name='Donneur')),
            ],
            options={
                'verbose_name': "Réponse d'un donneur",
                'verbose_name_plural': 'Réponses des donneurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_on', models.DateField(verbose_name='Date du don')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='sang.bloodrequest', verbose_name='Demande satisfaite')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='users.healthfacility', verbose_name='Lieu du don')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='sang.donor', verbose_name='Donneur')),
                ('response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation', to='sang.donorresponse', verbose_name="Réponse à l'origine du don")),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-donated_on', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['status', 'blood_group'], name='idx_bloodreq_status_group'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['facility', 'status'], name='idx_bloodreq_facility_status'),
        ),
        migrations.AddConstraint(
            model_name='bloodrequest',
            constraint=models.CheckConstraint(condition=models.Q(('units_needed__gte', 1), ('units_needed__lte', 50)), name='blood_request_units_needed_range'),
        ),
        migrations.AddConstraint(
            model_name='bloodrequest',
            constraint=models.CheckConstraint(condition=models.Q(('units_collected__lte', models.F('units_needed'))), name='blood_request_collected_lte_needed'),
        ),
        migrations.AddConstraint(
            model_name='bloodrequest',
            constraint=models.CheckConstraint(condition=models.Q(('search_radius_km__gte', 1), ('search_radius_km__lte', 200)), name='blood_request_radius_range'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_group', 'is_available'], name='idx_donor_group_available'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__gte', -90.0), ('latitude__isnull', False), ('latitude__lte', 90.0), ('longitude__gte', -180.0), ('longitude__isnull', False), ('longitude__lte', 180.0)), models.Q(('latitude__isnull', True), ('longitude__isnull', True)), _connector='OR'), name='donor_coordinates_valid'),
        ),
        migrations.AddConstraint(
            model_name='donorresponse',
            constraint=models.UniqueConstraint(fields=('blood_request', 'donor'), name='uniq_response_request_donor'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', '-donated_on'], name='idx_donation_donor_date'),
        ),
    ]
