# Generated by Django 6.1.1 on 2026-09-11 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True, verbose_name='Version')),
                ('algorithm', models.CharField(default='RandomForestRegressor', max_length=100, verbose_name='Algorithme')),
                ('trained_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'entraînement")),
                ('training_samples', models.PositiveIntegerField(default=0, verbose_name="Nombre d'échantillons d'entraînement")),
                ('mae', models.FloatField(default=0.0, verbose_name='MAE (Mean Absolute Error)')),
                ('rmse', models.FloatField(default=0.0, verbose_name='RMSE (Root Mean Squared Error)')),
                ('r2_score', models.FloatField(default=0.0, verbose_name='R² Score')),
                ('model_file_path', models.CharField(max_length=500, verbose_name='Chemin du fichier modèle')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si c'est le modèle utilisé pour les prédictions.", verbose_name='Modèle actif')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Métadonnées du modèle ML',
                'verbose_name_plural': 'Métadonnées des modèles ML',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(help_text='Nom complet du centre de transfusion sanguine.', max_length=200, verbose_name='Nom du centre de transfusion')),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('saint_louis', 'Saint-Louis'), ('kaolack', 'Kaolack'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('sedhiou', 'Sédhiou'), ('diourbel', 'Diourbel')], help_text='Région administrative du Sénégal.', max_length=50, verbose_name='Région')),
                ('blood_group', models.CharField(choices=[('A+', 'A Positif'), ('A-', 'A Négatif'), ('B+', 'B Positif'), ('B-', 'B Négatif'), ('AB+', 'AB Positif'), ('AB-', 'AB Négatif'), ('O+', 'O Positif'), ('O-', 'O Négatif')], max_length=3, verbose_name='Groupe sanguin')),
                ('date', models.DateField(help_text="Date de l'enregistrement du stock.", verbose_name='Date')),
                ('units_available', models.PositiveIntegerField(help_text='Nombre de poches de sang disponibles.', verbose_name='Unités disponibles')),
                ('units_donated', models.PositiveIntegerField(default=0, help_text='Nombre de poches reçues par don ce jour.', verbose_name='Unités reçues (dons)')),
                ('units_used', models.PositiveIntegerField(default=0, help_text='Nombre de poches utilisées (transfusions) ce jour.', verbose_name='Unités utilisées')),
                ('units_expired', models.PositiveIntegerField(default=0, help_text='Nombre de poches périmées retirées ce jour.', verbose_name='Unités périmées')),
            ],
            options={
                'verbose_name': 'Enregistrement de stock sanguin',
                'verbose_name_plural': 'Enregistrements de stock sanguin',
                'ordering': ['-date', 'region', 'blood_group'],
                'indexes': [models.Index(fields=['region', 'blood_group', 'date'], name='idx_stock_region_group_date'), models.Index(fields=['date'], name='idx_stock_date')],
                'unique_together': {('center_name', 'blood_group', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=200, verbose_name='Centre de transfusion')),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('saint_louis', 'Saint-Louis'), ('kaolack', 'Kaolack'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('sedhiou', 'Sédhiou'), ('diourbel', 'Diourbel')], max_length=50, verbose_name='Région')),
                ('blood_group', models.CharField(choices=[('A+', 'A Positif'), ('A-', 'A Négatif'), ('B+', 'B Positif'), ('B-', 'B Négatif'), ('AB+', 'AB Positif'), ('AB-', 'AB Négatif'), ('O+', 'O Positif'), ('O-', 'O Négatif')], max_length=3, verbose_name='Groupe sanguin')),
                ('prediction_date', models.DateField(help_text='La date pour laquelle la prédiction est faite.', verbose_name='Date prédite')),
                ('predicted_units', models.FloatField(help_text="Nombre d'unités de sang prédit pour cette date.", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unités prédites')),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critique — Pénurie imminente'), ('WARNING', 'Attention — Stock bas'), ('NORMAL', 'Normal — Stock suffisant')], max_length=10, verbose_name='Niveau de risque')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confiance du modèle dans cette prédiction (0 à 1).', verbose_name='Score de confiance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('model_version', models.CharField(default='1.0.0', max_length=50, verbose_name='Version du modèle')),
            ],
            options={
                'verbose_name': 'Prédiction',
                'verbose_name_plural': 'Prédictions',
                'ordering': ['-created_at', 'risk_level'],
                'indexes': [models.Index(fields=['region', 'blood_group', 'prediction_date'], name='idx_pred_region_group_date'), models.Index(fields=['risk_level', 'prediction_date'], name='idx_pred_risk_date')],
            },
        ),
    ]
