# Generated by Django 6.1.1 on 2026-09-27 20:45

import django.core.validators
from django.db import migrations, models


def delete_obsolete_predictions(apps, schema_editor):
    """Supprime les prédictions du modèle v1.

    Elles provenaient d'un modèle entraîné avec fuite de données et de seuils
    absolus ; ce sont des données dérivées, recalculées par
    ``python manage.py predict_shortages``.
    """
    apps.get_model('ml', 'PredictionResult').objects.all().delete()


def keep_single_active_model(apps, schema_editor):
    """Ne garde actif que le modèle le plus récent (prépare la contrainte)."""
    metadata = apps.get_model('ml', 'MLModelMetadata')
    latest = metadata.objects.filter(is_active=True).order_by('-trained_at').first()
    if latest is not None:
        metadata.objects.filter(is_active=True).exclude(pk=latest.pk).update(
            is_active=False
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionresult',
            options={'ordering': ['prediction_date', 'risk_level'], 'verbose_name': 'Prédiction', 'verbose_name_plural': 'Prédictions'},
        ),
        migrations.AlterUniqueTogether(
            name='bloodstockrecord',
            unique_together=set(),
        ),
        # Avant cette migration, l'historique provenait du générateur :
        # les lignes existantes sont marquées « synthetic », les nouvelles
        # lignes sont « manual » par défaut.
        migrations.AddField(
            model_name='bloodstockrecord',
            name='source',
            field=models.CharField(choices=[('synthetic', 'Synthétique (simulation)'), ('import', 'Import de fichier'), ('manual', 'Saisie manuelle')], default='synthetic', help_text='Origine de la donnée (simulation, import, saisie).', max_length=20, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='bloodstockrecord',
            name='source',
            field=models.CharField(choices=[('synthetic', 'Synthétique (simulation)'), ('import', 'Import de fichier'), ('manual', 'Saisie manuelle')], default='manual', help_text='Origine de la donnée (simulation, import, saisie).', max_length=20, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='mlmodelmetadata',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Évaluation sur période de test (baseline, couverture, alertes).', verbose_name='Métriques détaillées'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='days_of_supply',
            field=models.FloatField(blank=True, help_text='Stock prévu divisé par la consommation quotidienne moyenne.', null=True, verbose_name='Jours de stock'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='lower_bound',
            field=models.FloatField(blank=True, help_text="Stock sous lequel la valeur réelle a 10 % de chances d'être.", null=True, verbose_name='Borne basse (P10)'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='upper_bound',
            field=models.FloatField(blank=True, help_text="Stock au-dessus duquel la valeur réelle a 10 % de chances d'être.", null=True, verbose_name='Borne haute (P90)'),
        ),
        migrations.AlterField(
            model_name='bloodstockrecord',
            name='units_available',
            field=models.PositiveIntegerField(help_text='Nombre de poches disponibles en fin de journée.', verbose_name='Unités disponibles'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='algorithm',
            field=models.CharField(default='HistGradientBoostingRegressor', max_length=100, verbose_name='Algorithme'),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='model_file_path',
            field=models.CharField(max_length=500, verbose_name='Fichier du modèle'),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Probabilité estimée que le niveau de risque soit correct (0 à 1).', verbose_name='Score de confiance'),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='predicted_units',
            field=models.FloatField(help_text='Stock prévu (poches) pour cette date.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unités prédites'),
        ),
        migrations.RunPython(delete_obsolete_predictions, migrations.RunPython.noop),
        migrations.RunPython(keep_single_active_model, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='bloodstockrecord',
            constraint=models.UniqueConstraint(fields=('center_name', 'blood_group', 'date'), name='uniq_stock_center_group_date'),
        ),
        migrations.AddConstraint(
            model_name='mlmodelmetadata',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_ml_model'),
        ),
        migrations.AddConstraint(
            model_name='predictionresult',
            constraint=models.UniqueConstraint(fields=('center_name', 'blood_group', 'prediction_date'), name='uniq_prediction_center_group_date'),
        ),
    ]
