# Generated by Django 6.1.1 on 2026-09-29 20:43

import django.core.validators
import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='Enregistrée en majuscules, ex. DK-1234-AB.', max_length=20, unique=True, verbose_name='Immatriculation')),
                ('ambulance_type', models.CharField(choices=[('basic', 'Ambulance de transport'), ('medicalized', 'Ambulance médicalisée (SMUR)')], default='basic', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('on_mission', 'En mission'), ('out_of_service', 'Hors service')], default='available', max_length=20, verbose_name='Statut')),
                ('latitude', models.FloatField(blank=True, help_text='Degrés décimaux WGS 84 (-90 à 90).', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Degrés décimaux WGS 84 (-180 à 180).', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('location_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Position mise à jour le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to=settings.AUTH_USER_MODEL, verbose_name='Conducteur')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ambulances', to='users.healthfacility', verbose_name='Établissement de rattachement')),
            ],
            options={
                'verbose_name': 'Ambulance',
                'verbose_name_plural': 'Ambulances',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('critical', 'Critique (pronostic vital engagé)'), ('urgent', 'Urgente'), ('normal', 'Normale')], default='urgent', max_length=10, verbose_name='Priorité')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name="Nature de l'urgence")),
                ('pickup_address', models.CharField(blank=True, max_length=255, verbose_name="Lieu d'intervention")),
                ('pickup_latitude', models.FloatField(help_text='Degrés décimaux WGS 84 (-90 à 90).', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name="Latitude du lieu d'intervention")),
                ('pickup_longitude', models.FloatField(help_text='Degrés décimaux WGS 84 (-180 à 180).', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name="Longitude du lieu d'intervention")),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('saint_louis', 'Saint-Louis'), ('kaolack', 'Kaolack'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('sedhiou', 'Sédhiou'), ('diourbel', 'Diourbel')], max_length=50, verbose_name='Région')),
                ('caller_phone', models.CharField(blank=True, max_length=13, validators=[users.validators.validate_phone_number], verbose_name="Téléphone de l'appelant")),
                ('status', models.CharField(choices=[('pending', "En attente d'une ambulance"), ('assigned', 'Ambulance en route'), ('on_site', 'Ambulance sur place'), ('transporting', 'Transport du patient'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=15, verbose_name='Statut')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name="Motif d'annulation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Signalée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Affectée le')),
                ('on_site_at', models.DateTimeField(blank=True, null=True, verbose_name='Arrivée sur place le')),
                ('transporting_at', models.DateTimeField(blank=True, null=True, verbose_name="Départ vers l'établissement le")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Annulée le')),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='ambulances.ambulance', verbose_name='Ambulance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_missions', to='users.healthfacility', verbose_name='Établissement de destination')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ambulance',
            index=models.Index(fields=['status', 'ambulance_type'], name='idx_ambulance_status_type'),
        ),
        migrations.AddConstraint(
            model_name='ambulance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__gte', -90.0), ('latitude__isnull', False), ('latitude__lte', 90.0), ('longitude__gte', -180.0), ('longitude__isnull', False), ('longitude__lte', 180.0)), models.Q(('latitude__isnull', True), ('longitude__isnull', True)), _connector='OR'), name='ambulance_coordinates_valid'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['status', 'priority'], name='idx_mission_status_priority'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['region', 'status'], name='idx_mission_region_status'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['assigned', 'on_site', 'transporting'])), fields=('ambulance',), name='uniq_active_mission_per_ambulance', violation_error_message='Cette ambulance est déjà engagée sur une mission.'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_latitude__gte', -90.0), ('pickup_latitude__isnull', False), ('pickup_latitude__lte', 90.0), ('pickup_longitude__gte', -180.0), ('pickup_longitude__isnull', False), ('pickup_longitude__lte', 180.0)), name='mission_pickup_coordinates_valid'),
        ),
    ]
