# Generated by Django 6.1.1 on 2026-10-04 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Jeton Expo, ex. ExponentPushToken[xxxxxxxx].', max_length=255, unique=True, verbose_name='Jeton push')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10, verbose_name='Plateforme')),
                ('is_active', models.BooleanField(default=True, help_text="Désactivé à la déconnexion ou quand le service push signale l'application désinstallée.", verbose_name='Actif')),
                ('last_error', models.CharField(blank=True, max_length=100, verbose_name='Dernière erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Vu le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Téléphone (push)',
                'verbose_name_plural': 'Téléphones (push)',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_push_user_active')],
            },
        ),
    ]
