# Generated by Django 6.1.1 on 2026-09-29 20:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('emergency', 'Urgences'), ('intensive_care', 'Réanimation / soins intensifs'), ('surgery', 'Chirurgie'), ('internal_medicine', 'Médecine'), ('maternity', 'Maternité'), ('pediatrics', 'Pédiatrie'), ('neonatology', 'Néonatologie')], max_length=30, verbose_name='Service')),
                ('total_beds', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2000)], verbose_name='Lits installés')),
                ('occupied_beds', models.PositiveSmallIntegerField(default=0, verbose_name='Lits occupés')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_capacities', to='users.healthfacility', verbose_name='Établissement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Capacité en lits',
                'verbose_name_plural': 'Capacités en lits',
                'ordering': ['facility__name', 'category'],
                'indexes': [models.Index(fields=['category'], name='idx_bed_capacity_category')],
                'constraints': [models.UniqueConstraint(fields=('facility', 'category'), name='uniq_bed_capacity_facility_category', violation_error_message='Ce service existe déjà pour cet établissement.'), models.CheckConstraint(condition=models.Q(('occupied_beds__lte', models.F('total_beds'))), name='bed_capacity_occupied_lte_total', violation_error_message='Les lits occupés ne peuvent pas dépasser les lits installés.'), models.CheckConstraint(condition=models.Q(('total_beds__lte', 2000)), name='bed_capacity_total_max')],
            },
        ),
    ]
