# Generated by Django 6.1.1 on 2026-09-29 20:43

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('facility_type', models.CharField(choices=[('hospital', 'Hôpital'), ('health_center', 'Centre de santé'), ('clinic', 'Clinique'), ('blood_bank', 'Centre de transfusion sanguine'), ('ambulance_service', "Service d'ambulances")], max_length=30, verbose_name="Type d'établissement")),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('saint_louis', 'Saint-Louis'), ('kaolack', 'Kaolack'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('sedhiou', 'Sédhiou'), ('diourbel', 'Diourbel')], max_length=50, verbose_name='Région')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('phone_number', models.CharField(blank=True, help_text='Format international : +221XXXXXXXXX.', max_length=13, validators=[users.validators.validate_phone_number], verbose_name='Téléphone')),
                ('latitude', models.FloatField(help_text='Degrés décimaux WGS 84 (-90 à 90).', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Degrés décimaux WGS 84 (-180 à 180).', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, help_text="Un établissement inactif n'apparaît plus dans les recherches.", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Établissement de santé',
                'verbose_name_plural': 'Établissements de santé',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['region', 'facility_type'], name='idx_facility_region_type')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('region'), name='uniq_facility_name_region', violation_error_message='Un établissement porte déjà ce nom dans cette région.'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90.0), ('latitude__isnull', False), ('latitude__lte', 90.0), ('longitude__gte', -180.0), ('longitude__isnull', False), ('longitude__lte', 180.0)), name='facility_coordinates_valid')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Format international : +221XXXXXXXXX.', max_length=13, null=True, unique=True, validators=[users.validators.validate_phone_number], verbose_name='Téléphone')),
                ('region', models.CharField(blank=True, choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('saint_louis', 'Saint-Louis'), ('kaolack', 'Kaolack'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('sedhiou', 'Sédhiou'), ('diourbel', 'Diourbel')], help_text='Utilisée pour cibler les alertes régionales.', max_length=50, verbose_name='Région de résidence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('facility', models.ForeignKey(blank=True, help_text='Obligatoire pour le personnel hospitalier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='users.healthfacility', verbose_name='Établissement de rattachement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
